# Situazione regionale in Italia

```{r include=FALSE}
library(covidregionaldata)
library(tmap)
library(sf)
regions <- c("Trentino-Alto Adige", "Veneto", "Lombardia")
```

## Serie storica

Di seguito le serie storiche filtrate per le regioni `r regions`.

```{r message=FALSE, warning=FALSE}
ita <- get_regional_data("italy") %>% 
  select(regioni, date, cases_new, deaths_new) %>%
  rename(region=regioni)

# Raggruppo i dati per regione e applico kernel smoothing
ita_f <- ita %>% 
  group_by(region) %>%
  mutate(
    cases_new = ksmooth(date, cases_new, "normal", bandwidth=7)$y,
    deaths_new = ksmooth(date, deaths_new, "normal", bandwidth=7)$y)

# Seleziono regioni
ita_f_sel <- ita_f %>%
  filter(region %in% regions) 

# Plotto contagi
ita_f_sel %>%
  ggplot(aes(x=date, y=cases_new, color=region)) + 
  geom_line() +
  labs(x = "Data", y="Nuovi contagi", color="Regione") +
  scale_x_date(date_breaks = "1 month", labels=scales::label_date("%d %b")) +
  scale_y_continuous(labels = scales::label_number_si()) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plotto decessi
ita_f_sel %>%
  ggplot(aes(x=date, y=deaths_new, color=region)) + 
  geom_line() +
  labs(x = "Data", y="Decessi", color="Regione") +
  scale_x_date(date_breaks = "1 month", labels=scales::label_date("%d %b")) +
  scale_y_continuous(labels = scales::label_number_si()) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Mappa regionale

I seguenti dati rappresentano il numero di contagi  e dei decessi degli ultimi 7 giorni, regione per regione.

```{r message=FALSE, warning=FALSE}
# Dati degli ultimi 7 giorni
sit_7 <- ita %>%
  group_by(region) %>%
  slice_tail(n=7) %>%
  summarise(sum_c=sum(cases_new), sum_d=sum(deaths_new))

# Mappa tematica italiana
shapefile <- "data/ITA_adm1.shp"
if (!file.exists(shapefile)) {
  zipfile <- "data.zip"
  download.file("https://stacks.stanford.edu/file/druid:bb489fv3314/data.zip", zipfile)
  unzip(zipfile, exdir="data")
  file.remove(zipfile)
}
italy <- read_sf("data/ITA_adm1.shp")
# Semplifico la mappa per velocizzare il plottaggio (tengo il 10% dei punti)
italy <- rmapshaper::ms_simplify(italy, keep=0.1)
italy$NAME_1[italy$NAME_1 == "Apulia"] <- "Puglia"
italy$NAME_1[italy$NAME_1 == "Friuli-Venezia Giulia"] <- "Friuli Venezia Giulia"
italy$NAME_1[italy$NAME_1 == "Sicily"] <- "Sicilia"

# Popolazione estratta da censimento 2011
library(readr)
pop_regioni <- read_csv("pop_regioni.csv", 
    col_types = cols(Popolazione = col_double(), 
        Superficie = col_double(), Densità = col_double(), 
        N_comuni = col_integer(), N_provincie = col_integer()))

# Unisco le tabelle
italy <- italy %>% 
  left_join(sit_7, by=c("NAME_1"="region")) %>% 
  left_join(pop_regioni, by=c("NAME_1"="Regione")) %>%
  mutate(sum_c_pt=sum_c/Popolazione*1000) %>%
  relocate(sum_c, sum_d, Popolazione, .after="NAME_1")
```


```{r message=FALSE, warning=FALSE}
# Creo la mappa tematica
it_map <- tm_shape(italy) +
  tm_borders() 
m1 <- it_map +
  tm_fill(col="sum_c", title="Numero") +
  tm_layout(frame=F,
            title="Contagi settimanali", 
            legend.position = c("left", "bottom"),
            legend.format = list(text.separator="-"))
m2 <- it_map +
  tm_fill(col="sum_d", title="Numero") +
  tm_layout(frame=F,
            title="Decessi settimanali", 
            legend.position = c("left", "bottom"),
            legend.format = list(text.separator="-"))
m3 <- it_map +
  tm_fill(col="sum_c_pt", title="Numero/1000") +
  tm_layout(frame=F,
            title="Contagi sett./1000", 
            legend.position = c("left", "bottom"),
            legend.format = list(text.separator="-"))
tmap_arrange(m1, m3, m2)
```

